# Generated by Django 4.2 on 2023-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory_of_the_employees_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place_stay', models.CharField(max_length=100, verbose_name='name_place_stay')),
            ],
            options={
                'verbose_name': 'Directory_of_the_employees_location',
            },
        ),
        migrations.CreateModel(
            name='Main_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='employee_name')),
                ('vacant_name', models.CharField(max_length=50, verbose_name='vacant_name')),
                ('name_place_stay', models.CharField(max_length=100, verbose_name='name_place_stay')),
                ('vacant_end_date', models.DateField(verbose_name='vacant_end_date')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_directory_employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('staff_number', models.IntegerField(verbose_name='staff_number')),
                ('date_of_birth', models.DateField(verbose_name='date_of_birth')),
                ('cellphone', models.IntegerField(verbose_name='cellphone')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='place_of_birth')),
                ('address_of_actual_residence', models.TextField(max_length=100, verbose_name='address_of_actual_residence')),
                ('enrollment_date', models.DateField(verbose_name='enrollment_date')),
                ('actual_rank', models.CharField(max_length=50, verbose_name='actual_rank')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('reference_information', models.TextField(max_length=150, verbose_name='reference information')),
                ('position', models.CharField(max_length=50, verbose_name='position')),
            ],
            options={
                'verbose_name': 'Staff_directory_employee',
            },
        ),
        migrations.CreateModel(
            name='vacant_positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacant_name', models.CharField(max_length=50, verbose_name='vacant_name')),
                ('vacant_place', models.CharField(max_length=100, verbose_name='vacant_place')),
                ('vacant_date', models.DateField(verbose_name='vacant_date')),
            ],
        ),
    ]
