# Generated by Django 4.2 on 2023-04-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_directory_of_the_employees_location_main_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='freelance_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=50, verbose_name='work_name')),
                ('work_date', models.DateField(verbose_name='work_date')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacant_positions',
            name='vacant_date',
        ),
        migrations.RemoveField(
            model_name='vacant_positions',
            name='vacant_place',
        ),
    ]
