# Generated by Django 4.2 on 2023-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_freelance_work_remove_vacant_positions_vacant_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='employee_name')),
                ('work_name', models.CharField(max_length=50, verbose_name='work_name')),
                ('work_date', models.DateField(verbose_name='work_date')),
            ],
        ),
        migrations.RenameField(
            model_name='vacant_positions',
            old_name='vacant_name',
            new_name='name_vacant_position',
        ),
    ]
