# Generated by Django 4.2 on 2023-04-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_edit_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_report',
            name='vacant_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='vacant_end_date'),
        ),
        migrations.AlterField(
            model_name='main_report',
            name='vacant_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='vacant_name'),
        ),
    ]
