# Generated by Django 4.2 on 2023-04-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_main_report_vacant_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_report',
            options={'verbose_name': 'Main_report', 'verbose_name_plural': 'Main_report'},
        ),
    ]
