# Generated by Django 4.1.5 on 2023-04-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_remove_edit_report_work_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_report',
            name='work_date_end',
            field=models.DateTimeField(verbose_name='work_date_end'),
        ),
        migrations.AlterField(
            model_name='freelance_work',
            name='work_date_end',
            field=models.DateTimeField(verbose_name='work_date_end'),
        ),
    ]
