# Generated by Django 4.1.5 on 2023-04-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_edit_report_work_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_report',
            name='work_date_end',
            field=models.DateTimeField(null=True, verbose_name='work_date_end'),
        ),
    ]
