# Generated by Django 4.1.5 on 2023-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_alter_edit_report_work_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_report',
            name='work_name',
            field=models.CharField(max_length=50, null=True, verbose_name='work_name'),
        ),
    ]
