# Generated by Django 4.1.5 on 2023-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_edit_report_work_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_report',
            name='work_date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='work_date_end'),
        ),
        migrations.AlterField(
            model_name='edit_report',
            name='work_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='work_name'),
        ),
    ]
