# Generated by Django 4.1.5 on 2023-04-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_delete_directory_of_the_employees_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_directory_employees',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.vacant_positions'),
        ),
    ]
