# Generated by Django 4.1.5 on 2023-04-09 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_staff_directory_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_report',
            name='work_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.freelance_work'),
        ),
    ]
